export interface DefaultPricingPlan {
  name: string;
  description: string;
  price: number;
  price_suffix: string;
  features: string[];
  is_highlighted: boolean;
  is_visible: boolean;
  show_from: boolean;
  order: number;
}

export interface DefaultPricingService {
  name: string;
  description: string;
  price: number;
  price_suffix: string;
  category: string;
  is_visible: boolean;
  show_from: boolean;
  order: number;
}

export const defaultPricingPlans: DefaultPricingPlan[] = [
  {
    name: "Inmobiliario Esencial",
    description: "Sesión ágil para vivienda estándar, alquiler o venta con entrega rápida para portales.",
    price: 180,
    price_suffix: "/inmueble",
    features: [
      "15-25 fotografías editadas",
      "Corrección de color, luz y perspectiva",
      "Entrega habitual en 48-72 horas",
      "Licencia para web, portales y redes propias",
    ],
    is_highlighted: false,
    is_visible: true,
    show_from: true,
    order: 10,
  },
  {
    name: "Inmobiliario Premium",
    description: "Pack recomendado para propiedades con mayor valor visual, exteriores o necesidad de destacar.",
    price: 350,
    price_suffix: "/inmueble",
    features: [
      "Fotografía inmobiliaria premium",
      "Tomas de dron si la ubicación lo permite",
      "Selección ampliada y edición avanzada",
      "Material preparado para portales, web y redes",
    ],
    is_highlighted: true,
    is_visible: true,
    show_from: true,
    order: 20,
  },
  {
    name: "Producción Empresa",
    description: "Producción visual para empresas, hoteles, restaurantes, campañas o comunicación corporativa.",
    price: 800,
    price_suffix: "/proyecto",
    features: [
      "Briefing y recomendación de alcance",
      "Rodaje de fotografía, vídeo o contenido mixto",
      "Edición profesional y versiones para canales digitales",
      "Plan de entregables orientado a conversión",
    ],
    is_highlighted: false,
    is_visible: true,
    show_from: true,
    order: 30,
  },
];

export const defaultPricingServices: DefaultPricingService[] = [
  {
    name: "Fotografía inmobiliaria estándar",
    description: "Sesión para vivienda estándar con interiores, exteriores principales y edición para portales.",
    price: 180,
    price_suffix: "/inmueble",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 100,
  },
  {
    name: "Fotografía inmobiliaria premium",
    description: "Cobertura ampliada para inmuebles de alto valor, viviendas turísticas o espacios con más detalle visual.",
    price: 280,
    price_suffix: "/inmueble",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 110,
  },
  {
    name: "Fotografía inmobiliaria para alquiler vacacional",
    description: "Reportaje optimizado para Airbnb, Booking y alojamientos turísticos, con énfasis en amplitud, luz y servicios.",
    price: 220,
    price_suffix: "/inmueble",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 115,
  },
  {
    name: "Fotografía de arquitectura e interiorismo",
    description: "Reportaje cuidado para estudios, arquitectos, interioristas, hoteles y espacios comerciales.",
    price: 350,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 120,
  },
  {
    name: "Fotografía de hotel y alojamientos",
    description: "Cobertura de habitaciones, zonas comunes, restauración, exteriores y detalles para web, OTAs y campañas.",
    price: 550,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 125,
  },
  {
    name: "Fotografía de producto y ecommerce",
    description: "Imágenes de producto para catálogo, tienda online, campañas o marketplaces.",
    price: 250,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 130,
  },
  {
    name: "Pack ecommerce hasta 20 productos",
    description: "Fotografía homogénea de hasta 20 productos sobre fondo sencillo, con edición y entrega para tienda online.",
    price: 280,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 132,
  },
  {
    name: "Pack ecommerce hasta 50 productos",
    description: "Producción eficiente de catálogo para hasta 50 productos con iluminación y edición consistentes.",
    price: 480,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 135,
  },
  {
    name: "Fotografía gastronómica",
    description: "Sesión para restaurantes, cartas, delivery, hoteles y campañas de hostelería.",
    price: 280,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 140,
  },
  {
    name: "Fotografía gastronómica de carta completa",
    description: "Producción de una selección amplia de platos, ambiente y detalles para carta, web, delivery y redes.",
    price: 520,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 145,
  },
  {
    name: "Fotografía de moda y lookbook",
    description: "Producción para lookbooks, catálogo, editorial, ecommerce o marca personal.",
    price: 450,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 150,
  },
  {
    name: "Retrato corporativo y headshots",
    description: "Retratos profesionales para equipos, directivos, LinkedIn, web corporativa y prensa.",
    price: 220,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 160,
  },
  {
    name: "Headshots de equipo hasta 10 personas",
    description: "Retratos coherentes de hasta 10 personas en las instalaciones del cliente o localización acordada.",
    price: 450,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 165,
  },
  {
    name: "Fotografía industrial y corporativa",
    description: "Reportaje de instalaciones, procesos, equipos y comunicación empresarial.",
    price: 450,
    price_suffix: "/jornada",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 170,
  },
  {
    name: "Fotografía corporativa media jornada",
    description: "Cobertura de equipo, instalaciones, procesos y retratos durante una producción de hasta media jornada.",
    price: 450,
    price_suffix: "/media jornada",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 172,
  },
  {
    name: "Fotografía corporativa jornada completa",
    description: "Producción corporativa extendida para varias localizaciones, departamentos o necesidades de comunicación.",
    price: 750,
    price_suffix: "/jornada",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 174,
  },
  {
    name: "Fotografía de eventos 2 horas",
    description: "Cobertura breve para presentaciones, inauguraciones, encuentros de empresa o pequeños actos.",
    price: 220,
    price_suffix: "/evento",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 175,
  },
  {
    name: "Fotografía de eventos 4 horas",
    description: "Cobertura fotográfica para presentaciones, congresos, ferias, inauguraciones o actos de empresa.",
    price: 400,
    price_suffix: "/evento",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 180,
  },
  {
    name: "Fotografía de eventos día completo",
    description: "Cobertura extendida con selección editada para comunicación, prensa, web y redes.",
    price: 800,
    price_suffix: "/evento",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 190,
  },
  {
    name: "Reportaje de boda esencial",
    description: "Cobertura fotográfica de boda con estilo documental y edición profesional.",
    price: 900,
    price_suffix: "/evento",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 200,
  },
  {
    name: "Vídeo inmobiliario",
    description: "Pieza audiovisual para venta o alquiler de inmuebles, alojamientos turísticos y propiedades premium.",
    price: 450,
    price_suffix: "/inmueble",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 300,
  },
  {
    name: "Vídeo inmobiliario vertical para redes",
    description: "Recorrido vertical breve de una propiedad, editado para Reels, Stories, TikTok o campañas sociales.",
    price: 350,
    price_suffix: "/inmueble",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 305,
  },
  {
    name: "Vídeo corporativo",
    description: "Vídeo para presentar empresa, equipo, instalaciones, servicio, marca o caso de éxito.",
    price: 800,
    price_suffix: "/proyecto",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 310,
  },
  {
    name: "Entrevista o testimonio corporativo",
    description: "Grabación y edición de una entrevista, testimonio de cliente, caso de éxito o pieza de liderazgo.",
    price: 550,
    price_suffix: "/pieza",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 312,
  },
  {
    name: "Vídeo de producto o demostración",
    description: "Pieza audiovisual para explicar, lanzar o demostrar un producto o servicio en web, ventas o campañas.",
    price: 650,
    price_suffix: "/proyecto",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 314,
  },
  {
    name: "Vídeo publicitario o spot",
    description: "Producción con mayor planificación creativa para campañas, lanzamientos o publicidad digital.",
    price: 1200,
    price_suffix: "/proyecto",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 320,
  },
  {
    name: "Reels y piezas para redes",
    description: "Pieza corta vertical u horizontal para Instagram, TikTok, LinkedIn, YouTube Shorts o campañas.",
    price: 350,
    price_suffix: "/pieza",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 330,
  },
  {
    name: "Pack de 4 reels",
    description: "Producción coordinada de cuatro piezas cortas para redes con grabación y edición consistente.",
    price: 900,
    price_suffix: "/pack",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 332,
  },
  {
    name: "Pack de 8 reels",
    description: "Producción mensual o por campaña de ocho piezas verticales optimizadas para redes sociales.",
    price: 1600,
    price_suffix: "/pack",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 334,
  },
  {
    name: "Grabación aérea con dron",
    description: "Tomas aéreas profesionales en 4K, sujetas a viabilidad técnica y normativa de vuelo.",
    price: 350,
    price_suffix: "/sesión",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 340,
  },
  {
    name: "Fotografía aérea con dron",
    description: "Serie de fotografías aéreas editadas para inmobiliaria, turismo, industria, obra o comunicación corporativa.",
    price: 300,
    price_suffix: "/sesión",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 342,
  },
  {
    name: "Pack foto y vídeo con dron",
    description: "Captura combinada de fotografía y clips 4K en una misma operación, sujeta a viabilidad de vuelo.",
    price: 450,
    price_suffix: "/sesión",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 344,
  },
  {
    name: "Inspección visual con dron",
    description: "Captura técnica visual de cubiertas, fachadas, instalaciones u obra para revisión y documentación.",
    price: 450,
    price_suffix: "/operación",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 346,
  },
  {
    name: "Timelapse o seguimiento de obra",
    description: "Documentación de procesos, construcción, montaje o transformación de espacios.",
    price: 600,
    price_suffix: "/jornada",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 350,
  },
  {
    name: "Fotogrametría y modelado 3D con dron",
    description: "Captura aérea para modelos 3D, documentación técnica o visualización de terreno y edificios.",
    price: 750,
    price_suffix: "/proyecto",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 360,
  },
  {
    name: "Vídeo resumen de eventos",
    description: "Highlight audiovisual de congresos, ferias, presentaciones, bodas o eventos corporativos.",
    price: 700,
    price_suffix: "/evento",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 370,
  },
  {
    name: "Grabación íntegra de conferencia",
    description: "Registro completo de una ponencia, conferencia o formación con edición básica y entrega digital.",
    price: 550,
    price_suffix: "/evento",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 372,
  },
  {
    name: "Pack evento foto + vídeo resumen",
    description: "Cobertura combinada de fotografía y vídeo highlight para eventos corporativos, ferias o presentaciones.",
    price: 1100,
    price_suffix: "/evento",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 374,
  },
  {
    name: "Podcast de vídeo multicámara",
    description: "Grabación de videopodcast o entrevista larga con varias cámaras, audio cuidado y edición del episodio.",
    price: 550,
    price_suffix: "/sesión",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 376,
  },
  {
    name: "Tour virtual Matterport hasta 200 m²",
    description: "Escaneo Matterport para inmueble, comercio, oficina o espacio pequeño con tour navegable.",
    price: 250,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 500,
  },
  {
    name: "Tour virtual Matterport 200-500 m²",
    description: "Recorrido virtual 360 para espacios medianos, hoteles, restaurantes, oficinas o locales comerciales.",
    price: 450,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 510,
  },
  {
    name: "Tour virtual Matterport gran espacio",
    description: "Escaneo de espacios amplios, promociones, museos, coworkings, gimnasios o complejos turísticos.",
    price: 750,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 520,
  },
  {
    name: "Plano de planta y mediciones",
    description: "Plano orientativo y herramientas de medición asociadas al tour o al levantamiento del espacio.",
    price: 120,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 530,
  },
  {
    name: "Publicación en Google Street View",
    description: "Preparación y publicación de recorrido compatible para mejorar visibilidad local en Google.",
    price: 150,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 540,
  },
  {
    name: "Hosting o renovación Matterport",
    description: "Renovación anual orientativa del alojamiento del tour cuando no esté incluido en el proyecto.",
    price: 90,
    price_suffix: "/año",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 550,
  },
  {
    name: "Etiquetado y personalización de tour Matterport",
    description: "Alta de etiquetas, textos, enlaces, identidad visual y puntos informativos dentro de un tour existente.",
    price: 120,
    price_suffix: "/tour",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 560,
  },
  {
    name: "Render 3D fotorrealista",
    description: "Imagen 3D para arquitectura, interiorismo, promoción inmobiliaria o producto no construido.",
    price: 180,
    price_suffix: "/imagen",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 700,
  },
  {
    name: "Pack renders promoción inmobiliaria",
    description: "Conjunto de vistas 3D para presentar una promoción, vivienda piloto o propuesta comercial.",
    price: 900,
    price_suffix: "/proyecto",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 710,
  },
  {
    name: "Visualización de producto 3D",
    description: "Modelado y render para producto, catálogo, web, campaña o presentación comercial.",
    price: 350,
    price_suffix: "/modelo",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 720,
  },
  {
    name: "Panorámica 360 fotorrealista",
    description: "Imagen panorámica 3D navegable para presentar interiores, promociones o espacios todavía no construidos.",
    price: 320,
    price_suffix: "/imagen",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 730,
  },
  {
    name: "Home staging virtual",
    description: "Amueblado y estilismo digital de una estancia vacía o desactualizada para mejorar su presentación comercial.",
    price: 80,
    price_suffix: "/imagen",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 740,
  },
  {
    name: "Streaming profesional básico",
    description: "Retransmisión sencilla para eventos, charlas, presentaciones o reuniones con una realización ligera.",
    price: 600,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 900,
  },
  {
    name: "Streaming multicámara",
    description: "Realización en directo con varias cámaras para congresos, eventos corporativos o conferencias.",
    price: 1200,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 910,
  },
  {
    name: "Grabación de conferencia o presentación",
    description: "Registro audiovisual de ponencia, formación, charla o presentación para uso posterior.",
    price: 500,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 920,
  },
  {
    name: "Webinar o formación online",
    description: "Realización y soporte audiovisual para webinar, masterclass o formación retransmitida online.",
    price: 450,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 930,
  },
  {
    name: "Streaming multicámara premium",
    description: "Realización avanzada con varias cámaras, grafismo, contenidos remotos y soporte técnico ampliado.",
    price: 1800,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 940,
  },
  {
    name: "Preproducción y guion",
    description: "Definición de concepto, estructura narrativa, necesidades de rodaje y lista de entregables.",
    price: 250,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1100,
  },
  {
    name: "Edición avanzada o retoque extra",
    description: "Trabajo adicional de postproducción, retoque complejo, montaje o adaptación de piezas.",
    price: 60,
    price_suffix: "/hora",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1110,
  },
  {
    name: "Entrega urgente 24-48h",
    description: "Prioridad de edición y entrega cuando el calendario del proyecto lo permita.",
    price: 120,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1120,
  },
  {
    name: "Desplazamiento fuera de zona base",
    description: "Coste orientativo de desplazamiento según distancia, tiempos, peajes, dietas o alojamiento.",
    price: 60,
    price_suffix: "/desplazamiento",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1130,
  },
  {
    name: "Licencia de uso ampliada",
    description: "Ampliación de derechos para campañas, medios pagados, terceros o usos no previstos inicialmente.",
    price: 150,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1140,
  },
  {
    name: "Gestión de permisos de dron",
    description: "Estudio de viabilidad, coordinación básica y preparación de permisos cuando sean necesarios.",
    price: 120,
    price_suffix: "/operación",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1150,
  },
  {
    name: "Operador adicional de cámara o fotografía",
    description: "Segundo operador para producciones que requieren cobertura simultánea, más ángulos o equipos separados.",
    price: 300,
    price_suffix: "/jornada",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1160,
  },
  {
    name: "Asistente de producción",
    description: "Apoyo en iluminación, equipo, coordinación de escena y logística durante la producción.",
    price: 180,
    price_suffix: "/jornada",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1170,
  },
  {
    name: "Maquillaje y estilismo",
    description: "Profesional de maquillaje y retoque de imagen para retrato, moda, entrevista o producción publicitaria.",
    price: 250,
    price_suffix: "/sesión",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1180,
  },
  {
    name: "Subtítulos y adaptación de idioma",
    description: "Creación e integración de subtítulos o adaptación básica de una pieza a otro idioma.",
    price: 90,
    price_suffix: "/pieza",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1190,
  },
  {
    name: "Locución profesional",
    description: "Grabación de voz profesional para vídeo corporativo, spot, presentación o contenido digital.",
    price: 180,
    price_suffix: "/pieza",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1200,
  },
  {
    name: "Licencia musical",
    description: "Licencia orientativa de música para una pieza audiovisual y sus canales de publicación acordados.",
    price: 90,
    price_suffix: "/pieza",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1210,
  },
  {
    name: "Entrega de material bruto",
    description: "Preparación y entrega organizada de los archivos originales cuando se acuerde expresamente.",
    price: 150,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1220,
  },
  {
    name: "Ronda adicional de cambios",
    description: "Ronda de revisión posterior a las incluidas inicialmente en el alcance del proyecto.",
    price: 75,
    price_suffix: "/ronda",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1230,
  },
  {
    name: "Adaptación a formato adicional",
    description: "Versión adicional de una pieza para otra relación de aspecto, duración o canal de publicación.",
    price: 50,
    price_suffix: "/pieza",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1240,
  },
  {
    name: "Trabajo nocturno o fin de semana",
    description: "Suplemento orientativo por producción fuera del horario habitual, sujeto a disponibilidad.",
    price: 150,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1250,
  },
];
