export interface DefaultPricingPlan {
  name: string;
  description: string;
  price: number;
  price_suffix: string;
  features: string[];
  is_highlighted: boolean;
  is_visible: boolean;
  show_from: boolean;
  order: number;
}

export interface DefaultPricingService {
  name: string;
  description: string;
  price: number;
  price_suffix: string;
  category: string;
  is_visible: boolean;
  show_from: boolean;
  order: number;
}

export const defaultPricingPlans: DefaultPricingPlan[] = [
  {
    name: "Inmobiliario Esencial",
    description: "Sesión ágil para vivienda estándar, alquiler o venta con entrega rápida para portales.",
    price: 180,
    price_suffix: "/inmueble",
    features: [
      "15-25 fotografías editadas",
      "Corrección de color, luz y perspectiva",
      "Entrega habitual en 48-72 horas",
      "Licencia para web, portales y redes propias",
    ],
    is_highlighted: false,
    is_visible: true,
    show_from: true,
    order: 10,
  },
  {
    name: "Inmobiliario Premium",
    description: "Pack recomendado para propiedades con mayor valor visual, exteriores o necesidad de destacar.",
    price: 350,
    price_suffix: "/inmueble",
    features: [
      "Fotografía inmobiliaria premium",
      "Tomas de dron si la ubicación lo permite",
      "Selección ampliada y edición avanzada",
      "Material preparado para portales, web y redes",
    ],
    is_highlighted: true,
    is_visible: true,
    show_from: true,
    order: 20,
  },
  {
    name: "Producción Empresa",
    description: "Producción visual para empresas, hoteles, restaurantes, campañas o comunicación corporativa.",
    price: 800,
    price_suffix: "/proyecto",
    features: [
      "Briefing y recomendación de alcance",
      "Rodaje de fotografía, vídeo o contenido mixto",
      "Edición profesional y versiones para canales digitales",
      "Plan de entregables orientado a conversión",
    ],
    is_highlighted: false,
    is_visible: true,
    show_from: true,
    order: 30,
  },
];

export const defaultPricingServices: DefaultPricingService[] = [
  {
    name: "Fotografía inmobiliaria estándar",
    description: "Sesión para vivienda estándar con interiores, exteriores principales y edición para portales.",
    price: 180,
    price_suffix: "/inmueble",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 100,
  },
  {
    name: "Fotografía inmobiliaria premium",
    description: "Cobertura ampliada para inmuebles de alto valor, viviendas turísticas o espacios con más detalle visual.",
    price: 280,
    price_suffix: "/inmueble",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 110,
  },
  {
    name: "Fotografía de arquitectura e interiorismo",
    description: "Reportaje cuidado para estudios, arquitectos, interioristas, hoteles y espacios comerciales.",
    price: 350,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 120,
  },
  {
    name: "Fotografía de producto y ecommerce",
    description: "Imágenes de producto para catálogo, tienda online, campañas o marketplaces.",
    price: 250,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 130,
  },
  {
    name: "Fotografía gastronómica",
    description: "Sesión para restaurantes, cartas, delivery, hoteles y campañas de hostelería.",
    price: 280,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 140,
  },
  {
    name: "Fotografía de moda y lookbook",
    description: "Producción para lookbooks, catálogo, editorial, ecommerce o marca personal.",
    price: 450,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 150,
  },
  {
    name: "Retrato corporativo y headshots",
    description: "Retratos profesionales para equipos, directivos, LinkedIn, web corporativa y prensa.",
    price: 220,
    price_suffix: "/sesión",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 160,
  },
  {
    name: "Fotografía industrial y corporativa",
    description: "Reportaje de instalaciones, procesos, equipos y comunicación empresarial.",
    price: 450,
    price_suffix: "/jornada",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 170,
  },
  {
    name: "Fotografía de eventos 4 horas",
    description: "Cobertura fotográfica para presentaciones, congresos, ferias, inauguraciones o actos de empresa.",
    price: 400,
    price_suffix: "/evento",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 180,
  },
  {
    name: "Fotografía de eventos día completo",
    description: "Cobertura extendida con selección editada para comunicación, prensa, web y redes.",
    price: 800,
    price_suffix: "/evento",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 190,
  },
  {
    name: "Reportaje de boda esencial",
    description: "Cobertura fotográfica de boda con estilo documental y edición profesional.",
    price: 900,
    price_suffix: "/evento",
    category: "Fotografía",
    is_visible: true,
    show_from: true,
    order: 200,
  },
  {
    name: "Vídeo inmobiliario",
    description: "Pieza audiovisual para venta o alquiler de inmuebles, alojamientos turísticos y propiedades premium.",
    price: 450,
    price_suffix: "/inmueble",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 300,
  },
  {
    name: "Vídeo corporativo",
    description: "Vídeo para presentar empresa, equipo, instalaciones, servicio, marca o caso de éxito.",
    price: 800,
    price_suffix: "/proyecto",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 310,
  },
  {
    name: "Vídeo publicitario o spot",
    description: "Producción con mayor planificación creativa para campañas, lanzamientos o publicidad digital.",
    price: 1200,
    price_suffix: "/proyecto",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 320,
  },
  {
    name: "Reels y piezas para redes",
    description: "Pieza corta vertical u horizontal para Instagram, TikTok, LinkedIn, YouTube Shorts o campañas.",
    price: 350,
    price_suffix: "/pieza",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 330,
  },
  {
    name: "Grabación aérea con dron",
    description: "Tomas aéreas profesionales en 4K, sujetas a viabilidad técnica y normativa de vuelo.",
    price: 350,
    price_suffix: "/sesión",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 340,
  },
  {
    name: "Timelapse o seguimiento de obra",
    description: "Documentación de procesos, construcción, montaje o transformación de espacios.",
    price: 600,
    price_suffix: "/jornada",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 350,
  },
  {
    name: "Fotogrametría y modelado 3D con dron",
    description: "Captura aérea para modelos 3D, documentación técnica o visualización de terreno y edificios.",
    price: 750,
    price_suffix: "/proyecto",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 360,
  },
  {
    name: "Vídeo resumen de eventos",
    description: "Highlight audiovisual de congresos, ferias, presentaciones, bodas o eventos corporativos.",
    price: 700,
    price_suffix: "/evento",
    category: "Vídeo y dron",
    is_visible: true,
    show_from: true,
    order: 370,
  },
  {
    name: "Tour virtual Matterport hasta 200 m²",
    description: "Escaneo Matterport para inmueble, comercio, oficina o espacio pequeño con tour navegable.",
    price: 250,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 500,
  },
  {
    name: "Tour virtual Matterport 200-500 m²",
    description: "Recorrido virtual 360 para espacios medianos, hoteles, restaurantes, oficinas o locales comerciales.",
    price: 450,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 510,
  },
  {
    name: "Tour virtual Matterport gran espacio",
    description: "Escaneo de espacios amplios, promociones, museos, coworkings, gimnasios o complejos turísticos.",
    price: 750,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 520,
  },
  {
    name: "Plano de planta y mediciones",
    description: "Plano orientativo y herramientas de medición asociadas al tour o al levantamiento del espacio.",
    price: 120,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 530,
  },
  {
    name: "Publicación en Google Street View",
    description: "Preparación y publicación de recorrido compatible para mejorar visibilidad local en Google.",
    price: 150,
    price_suffix: "/espacio",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 540,
  },
  {
    name: "Hosting o renovación Matterport",
    description: "Renovación anual orientativa del alojamiento del tour cuando no esté incluido en el proyecto.",
    price: 90,
    price_suffix: "/año",
    category: "Tours virtuales y 360",
    is_visible: true,
    show_from: true,
    order: 550,
  },
  {
    name: "Render 3D fotorrealista",
    description: "Imagen 3D para arquitectura, interiorismo, promoción inmobiliaria o producto no construido.",
    price: 180,
    price_suffix: "/imagen",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 700,
  },
  {
    name: "Pack renders promoción inmobiliaria",
    description: "Conjunto de vistas 3D para presentar una promoción, vivienda piloto o propuesta comercial.",
    price: 900,
    price_suffix: "/proyecto",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 710,
  },
  {
    name: "Visualización de producto 3D",
    description: "Modelado y render para producto, catálogo, web, campaña o presentación comercial.",
    price: 350,
    price_suffix: "/modelo",
    category: "Renders y 3D",
    is_visible: true,
    show_from: true,
    order: 720,
  },
  {
    name: "Streaming profesional básico",
    description: "Retransmisión sencilla para eventos, charlas, presentaciones o reuniones con una realización ligera.",
    price: 600,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 900,
  },
  {
    name: "Streaming multicámara",
    description: "Realización en directo con varias cámaras para congresos, eventos corporativos o conferencias.",
    price: 1200,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 910,
  },
  {
    name: "Grabación de conferencia o presentación",
    description: "Registro audiovisual de ponencia, formación, charla o presentación para uso posterior.",
    price: 500,
    price_suffix: "/evento",
    category: "Streaming y eventos",
    is_visible: true,
    show_from: true,
    order: 920,
  },
  {
    name: "Preproducción y guion",
    description: "Definición de concepto, estructura narrativa, necesidades de rodaje y lista de entregables.",
    price: 250,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1100,
  },
  {
    name: "Edición avanzada o retoque extra",
    description: "Trabajo adicional de postproducción, retoque complejo, montaje o adaptación de piezas.",
    price: 60,
    price_suffix: "/hora",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1110,
  },
  {
    name: "Entrega urgente 24-48h",
    description: "Prioridad de edición y entrega cuando el calendario del proyecto lo permita.",
    price: 120,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1120,
  },
  {
    name: "Desplazamiento fuera de zona base",
    description: "Coste orientativo de desplazamiento según distancia, tiempos, peajes, dietas o alojamiento.",
    price: 60,
    price_suffix: "/desplazamiento",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1130,
  },
  {
    name: "Licencia de uso ampliada",
    description: "Ampliación de derechos para campañas, medios pagados, terceros o usos no previstos inicialmente.",
    price: 150,
    price_suffix: "/proyecto",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1140,
  },
  {
    name: "Gestión de permisos de dron",
    description: "Estudio de viabilidad, coordinación básica y preparación de permisos cuando sean necesarios.",
    price: 120,
    price_suffix: "/operación",
    category: "Extras",
    is_visible: true,
    show_from: true,
    order: 1150,
  },
];
